graph LR
    A[External CSV Sources] --> B(Download)
    B --> C[(Hadoop)]
    C --> D[Spark Read]
    D --> E[Spark Processing]

    subgraph Spark Processing
        E --> F[Data Transformation]
        E --> G[Data Aggregation]
        F & G --> I[Spark DataFrame]
    end

    I --> K(InfluxDb)
    K --> L[(Dashboard)]
    A[External CSV Sources] --> J
    J[Daily Fetch Data  - Cron Job] --> K